In [2]:
import folium

location : 지도의 중심
zoom_start : 지도의 크기( 0 ~ 18 사용 )
tiles : 지도의 타일, Open Street Map, Stamen Terrain, Stamen Toner, 
(api key 요구 title : Mapbox Bright, Mapbox Control room tiles)

In [3]:
m=folium.Map(location=[35.137922, 129.055628],zoom_start=17,tiles='Open Street Map')
m.save('data/map1.html')
m

In [10]:
m=folium.Map(location=[35.137922, 129.055628],tiles='Stamen Toner')
m

In [11]:
m=folium.Map(location=[35.137922, 129.055628],tiles='Stamen Terrain')
m

In [13]:
folium.Marker([35.137922, 129.055628],popup='부산 중심 위치').add_to(m)
m

In [20]:
tooltip="클릭해주세요"
m=folium.Map(location=[35.137922, 129.055628],zoom_start=17,tiles='Open Street Map')
folium.Marker([35.136922, 129.055628],popup='가운데',tooltip=tooltip).add_to(m)
folium.Marker([35.137920, 129.055628],popup='위쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.138924, 129.055628],popup='아래쪽',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.054628],popup='부산 중심 위치',tooltip=tooltip).add_to(m)
folium.Marker([35.137922, 129.056628],popup='부산 중심 위치',tooltip=tooltip).add_to(m)
m

In [22]:
m=folium.Map(location=[37.564444, 126.975676], zoom_start=17)
folium.Marker([37.564444, 126.975676],popup='서울시청',
              icon=folium.Icon(color='red' , icon='info-sign')).add_to(m)
folium.CircleMarker([37.5658859, 126.9754788], radius=100, color="#3186cc",
                    fill_color='#cc8631', popup='덕수궁').add_to(m)
m

In [25]:
tooltip="클릭해주세요"
m=folium.Map(location=[37.564444, 126.975676], zoom_start=17, tiles='Stamen Toner')
folium.Marker([37.564444, 126.975676],popup='<i>서울시청</i>',
              icon=folium.Icon(color='red' , icon='cloud')).add_to(m)
folium.Marker([37.563444, 126.975676],popup='<i>서울시청</i>',
              icon=folium.Icon(color='red' , icon='star')).add_to(m)
folium.Marker([37.565444, 126.975676],popup='<i>서울시청</i>',
              icon=folium.Icon(color='red' , icon='default')).add_to(m)
m




In [24]:
help(folium.Icon)

Help on class Icon in module folium.map:

class Icon(branca.element.MacroElement)
 |  Icon(color='blue', icon_color='white', icon='info-sign', angle=0, prefix='glyphicon', **kwargs)
 |  
 |  Creates an Icon object that will be rendered
 |  using Leaflet.awesome-markers.
 |  
 |  Parameters
 |  ----------
 |  color : str, default 'blue'
 |      The color of the marker. You can use:
 |  
 |          ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
 |           'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
 |           'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
 |           'gray', 'black', 'lightgray']
 |  
 |  icon_color : str, default 'white'
 |      The color of the drawing on the marker. You can use colors above,
 |      or an html color code.
 |  icon : str, default 'info-sign'
 |      The name of the marker sign.
 |      See Font-Awesome website to choose yours.
 |      Warning : depending on the icon you choose you may need to adapt
 |      the `

In [26]:
m.add_child(folium.ClickForMarker(popup='마크'))
m

In [27]:
m.add_child(folium.LatLngPopup())
m

In [30]:
from folium import plugins
import os
import numpy as np

In [31]:
N=100
data=np.array(
    [np.random.uniform(low=35, high=38, size=N), 
     np.random.uniform(low=126, high=129, size=N)]
).T
data

array([[ 37.61721388, 127.99007558],
       [ 37.60282406, 127.78233391],
       [ 35.29672116, 128.91221862],
       [ 37.45960111, 126.7576951 ],
       [ 37.08682935, 127.38472196],
       [ 36.17678192, 127.13173525],
       [ 35.0340761 , 128.23138808],
       [ 35.66220215, 127.67837219],
       [ 35.17034659, 128.99946548],
       [ 37.83754854, 126.89303294],
       [ 35.67531275, 128.86260591],
       [ 36.39622129, 127.28495583],
       [ 36.72008113, 126.87161822],
       [ 37.71864589, 128.23591859],
       [ 37.47832739, 126.16502401],
       [ 35.82010858, 127.7010681 ],
       [ 36.51117269, 127.47525648],
       [ 36.79621436, 126.90728392],
       [ 36.11212964, 128.82969526],
       [ 35.09620955, 126.89685537],
       [ 36.82289534, 128.37451399],
       [ 35.73214841, 127.54066062],
       [ 35.55999669, 126.34972339],
       [ 37.14491369, 126.04254871],
       [ 35.60442602, 128.61153296],
       [ 35.84495997, 126.4898497 ],
       [ 35.86149141, 128.40357915],
 

In [34]:
popups=[str(i+1) for i in range(N)]
m=folium.Map(location=[37.564444, 126.975676], zoom_start=6)
plugins.MarkerCluster(data, popups=popups).add_to(m)
m.save(os.path.join('data', 'plugins_1.html'))
m

In [35]:
import pandas as pd

In [36]:
cctv=pd.read_csv("data/CCTV_20190917.csv")
cctv

관리기관명                 소재지도로명주소                소재지지번주소 설치목적구분  카메라대수  \
0   부산광역시 부산진구청       부산광역시 부산진구 성지로 116   부산광역시 부산진구 초읍동 178-6  어린이보호      1   
1   부산광역시 부산진구청    부산광역시 부산진구 안창로14번길 78    부산광역시 부산진구 범천동 1536  어린이보호      0   
2   부산광역시 부산진구청  부산광역시 부산진구 백양대로260번길 16   부산광역시 부산진구 개금동 419-3  어린이보호      0   
3   부산광역시 부산진구청    부산광역시 부산진구 양지로11번길 64   부산광역시 부산진구 양정동 345-2  어린이보호      1   
4   부산광역시 부산진구청     부산광역시 부산진구 국악로60번길 4  부산광역시 부산진구 초읍동 616-15  어린이보호      0   
..          ...                      ...                    ...    ...    ...   
84  부산광역시 부산진구청  부산광역시 부산진구 진사로61번길 28-7   부산광역시 부산진구 개금동 630-5  어린이보호      1   
85  부산광역시 부산진구청        부산광역시 부산진구 복지로 71  부산광역시 부산진구 개금동 565-14  어린이보호      0   
86  부산광역시 부산진구청   부산광역시 부산진구 성지로104번길 26     부산광역시 부산진구 초읍동 540  어린이보호      1   
87  부산광역시 부산진구청  부산광역시 부산진구 백양대로320번길 40  부산광역시 부산진구 개금동 446-14  어린이보호      1   
88  부산광역시 부산진구청   부산광역시 부산진구 백양순환로 70-11   부산광역시 부산진구 당감동 775-2  어린이보호      1   

    카메라화소수    촬영방면정보  보관일수  설치년월      관리기관전화번호         위도          경도  \
0    200.0  360도 전방면  30.0   NaN  051-605-4647  35.180330  129.051626   
1      NaN       NaN   NaN   NaN  051-605-4647  35.146126  129.043400   
2      NaN       NaN   NaN   NaN  051-605-4647  35.156511  129.022270   
3    200.0  360도 전방면  30.0   NaN  051-605-4647  35.171487  129.071727   
4      NaN       NaN   NaN   NaN  051-605-4647  35.174720  129.050461   
..     ...       ...   ...   ...           ...        ...         ...   
84   200.0  360도 전방면  30.0   NaN  051-605-4647  35.145796  129.019467   
85     NaN       NaN   NaN   NaN  051-605-4647  35.147113  129.018426   
86   200.0  360도 전방면  30.0   NaN  051-605-4647  35.180253  129.054447   
87   200.0  360도 전방면  30.0   NaN  051-605-4647  35.156259  129.015978   
88   200.0  360도 전방면  30.0   NaN  051-605-4647  35.168584  129.037950   

       데이터기준일자  
0   2019-09-17  
1   2019-09-17  
2   2019-09-17  
3   2019-09-17  
4   2019-09-17  
..         ...  
84  2019-09-17  
85  2019-09-17  
86  2019-09-17  
87  2019-09-17  
88  2019-09-17  

[89 rows x 13 columns]

In [39]:
popups=list(cctv.iloc[:,1])
popups

['부산광역시 부산진구 성지로 116',
 '부산광역시 부산진구 안창로14번길 78',
 '부산광역시 부산진구 백양대로260번길 16',
 '부산광역시 부산진구 양지로11번길 64',
 '부산광역시 부산진구 국악로60번길 4',
 '부산광역시 부산진구 거제대로 37',
 '부산광역시 부산진구 당감로 79',
 '부산광역시 부산진구 성지로14번길 65',
 '부산광역시 부산진구 백양대로208번길 174',
 '부산광역시 부산진구 개금본동로9번길 41',
 '부산광역시 부산진구 당감서로 16',
 '부산광역시 부산진구 백양관문로77번길 33',
 '부산광역시 부산진구 거제천로40번길 31',
 '부산광역시 부산진구 복지로 117-12',
 '부산광역시 부산진구 백양대로136번길 90',
 '부산광역시 부산진구 연수로11번길 34',
 '부산광역시 부산진구 백양대로136번길 37-9',
 '부산광역시 부산진구 동평로39번길 106',
 '부산광역시 부산진구 엄광로386번길 24',
 '부산광역시 부산진구 냉정로178번길 13',
 '부산광역시 부산진구 백양관문로 25-29',
 '부산광역시 부산진구 화지로 6',
 '부산광역시 부산진구 당감서로 120',
 '부산광역시 부산진구 백양관문로 112',
 '부산광역시 부산진구 복지로 70',
 '부산광역시 부산진구 성지로74번길 60',
 '부산광역시 부산진구 백양순환로18번길 36',
 '부산광역시 부산진구 당감로 22-5',
 '부산광역시 부산진구 당감서로100번길 56',
 '부산광역시 부산진구 동성로 26',
 '부산광역시 부산진구 당감로64번길 27',
 '부산광역시 부산진구 경마장로5번길 71',
 '부산광역시 부산진구 엄광로 122',
 '부산광역시 부산진구 진남로 506',
 '부산광역시 부산진구 범천로 30',
 '부산광역시 부산진구 새싹로14번길 7',
 '부산광역시 부산진구 엄광로182번길 15-14',
 '부산광역시 부산진구 성지로46번길 15',
 '부산광역시 부산진구 동평로183번길 114',


In [40]:
counts=list(cctv.iloc[:,4])
counts

[1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1]

In [42]:

lats=list(cctv.iloc[:,10])
longs=list(cctv.iloc[:,11])
print(lats)
print(longs)

lat_longs=np.array([lats,longs]).T
lat_longs

[35.1803305, 35.1461264, 35.1565111, 35.1714866, 35.1747205, 35.1720901, 35.1689816, 35.1733928, 35.1635902, 35.1571185, 35.1623331, 35.1644943, 35.1792288, 35.1426032, 35.1639901, 35.1747949, 35.1618761, 35.1676615, 35.1514439, 35.1492985, 35.1608238, 35.1755761, 35.1692452, 35.1684981, 35.1475527, 35.1790061, 35.1662387, 35.1643376, 35.1703418, 35.1519744, 35.1679636, 35.1707573, 35.1466982, 35.1685344, 35.1499601, 35.1597736, 35.1469879, 35.1749851, 35.1720278, 35.1661393, 35.1497283, 35.1515174, 35.1715531, 35.1637504, 35.1639901, 35.1711433, 35.1697015, 35.1745127, 35.1558713, 35.1506644, 35.1728515, 35.1594596, 35.1457956, 35.1814958, 35.1565783, 35.1542617, 35.1463446, 35.1534415, 35.1486791, 35.1544203, 35.1562594, 35.1645759, 35.1586337, 35.1584924, 35.1643376, 35.1615747, 35.1525298, 35.1763311, 35.1729525, 35.1673508, 35.1499593, 35.1650691, 35.1550139, 35.1487601, 35.1515174, 35.1452327, 35.1637147, 35.1644152, 35.1713838, 35.1704357, 35.1752436, 35.1721661, 35.1770072, 35.

array([[ 35.1803305, 129.0516257],
       [ 35.1461264, 129.0434004],
       [ 35.1565111, 129.0222699],
       [ 35.1714866, 129.0717271],
       [ 35.1747205, 129.0504611],
       [ 35.1720901, 129.0655534],
       [ 35.1689816, 129.0375669],
       [ 35.1733928, 129.0586357],
       [ 35.1635902, 129.0244649],
       [ 35.1571185, 129.0235693],
       [ 35.1623331, 129.0366197],
       [ 35.1644943, 129.0277604],
       [ 35.1792288, 129.0727223],
       [ 35.1426032, 129.0195381],
       [ 35.1639901, 129.0338286],
       [ 35.1747949, 129.0737388],
       [ 35.1618761, 129.0332321],
       [ 35.1676615, 129.0292801],
       [ 35.1514439, 129.0459936],
       [ 35.1492985, 129.0196731],
       [ 35.1608238, 129.0294651],
       [ 35.1755761, 129.0640828],
       [ 35.1692452, 129.0336184],
       [ 35.1684981, 129.0283234],
       [ 35.1475527, 129.0192145],
       [ 35.1790061, 129.0563305],
       [ 35.1662387, 129.0352533],
       [ 35.1643376, 129.0408295],
       [ 35.1703418,

In [43]:
print(len(popups), len(counts),lat_longs.shape)

89 89 (89, 2)


In [45]:
popups1, lat_longs1=[],[]
for i in range(len(counts)):
    if counts[i]>0:
        popups1.append(popups[i])
        lat_longs1.append(lat_longs[i])

print(len(popups1), len(lat_longs1))

lat_longs_arr=np.array(lat_longs1)
lat_longs_arr

70 70


array([[ 35.1803305, 129.0516257],
       [ 35.1714866, 129.0717271],
       [ 35.1635902, 129.0244649],
       [ 35.1571185, 129.0235693],
       [ 35.1623331, 129.0366197],
       [ 35.1644943, 129.0277604],
       [ 35.1792288, 129.0727223],
       [ 35.1426032, 129.0195381],
       [ 35.1639901, 129.0338286],
       [ 35.1747949, 129.0737388],
       [ 35.1618761, 129.0332321],
       [ 35.1676615, 129.0292801],
       [ 35.1492985, 129.0196731],
       [ 35.1608238, 129.0294651],
       [ 35.1755761, 129.0640828],
       [ 35.1692452, 129.0336184],
       [ 35.1475527, 129.0192145],
       [ 35.1662387, 129.0352533],
       [ 35.1703418, 129.0338837],
       [ 35.1679636, 129.0401347],
       [ 35.1707573, 129.0632483],
       [ 35.1466982, 129.0255141],
       [ 35.1499601, 129.0560701],
       [ 35.1597736, 129.0581321],
       [ 35.1749851, 129.0557922],
       [ 35.1661393, 129.0515033],
       [ 35.1497283, 129.0522612],
       [ 35.1715531, 129.0328583],
       [ 35.1639901,

In [50]:
tooltip="클릭해주세요"
m=folium.Map(location=[35.1803305, 129.0516257], zoom_start=12)
plugins.MarkerCluster(lat_longs_arr, popups=popups1).add_to(m)
m.save(os.path.join('data', 'cctv_1.html'))
m

# 버스위치정보 지도 시각화
- 공공데이터 활용
- 서울특별시 버스노선정보조회 서비스
- 서울특별시 버스위치정보조회 서비스

In [51]:
from bs4 import BeautifulSoup as bs
import urllib.request as req


In [52]:
busNum=504
key='bz6p9J0zjOTIbSrGsm6BH3B4i9IEW29rnGC6LNchn750ZVUpKW3HKr211MoqBZhOy02OyMRxsN60JqwPc0KpXQ=='
url='http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?serviceKey=%s&strSrch=%s'%(key,busNum)
savename='data/businfo.xml'
req.urlretrieve(url, savename)

('data/businfo.xml', <http.client.HTTPMessage at 0x159bdbe0f10>)

In [53]:
xml=open(savename, 'r', encoding='utf-8').read()
soup=bs(xml,'xml')
soup

<?xml version="1.0" encoding="utf-8"?>
<ServiceResult><comMsgHeader/><msgHeader><headerCd>0</headerCd><headerMsg>정상적으로 처리되었습니다.</headerMsg><itemCount>0</itemCount></msgHeader><msgBody><itemList><busRouteAbrv>504</busRouteAbrv><busRouteId>100100079</busRouteId><busRouteNm>504</busRouteNm><corpNm>한성운수  02-898-3542</corpNm><edStationNm>남대문</edStationNm><firstBusTm>20230427035500</firstBusTm><firstLowTm>20151125230000</firstLowTm><lastBusTm>20230427224000</lastBusTm><lastBusYn> </lastBusYn><lastLowTm>20150717035500</lastLowTm><length>44</length><routeType>3</routeType><stStationNm>광명공영주차장</stStationNm><term>7</term></itemList></msgBody></ServiceResult>

In [55]:
item_list=soup.find_all('itemList')
busRoute_id=''
for item in item_list:
    busRouteId=item.find('busRouteId').text
    busRouteNm=item.find('busRouteNm').text

    if busRouteNm.strip()==str(busNum):
        print(busRouteId, busRouteNm)
        busRoute_id=busRouteId
print(busRoute_id)

100100079 504
100100079


In [56]:
url='http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?serviceKey=%s&busRouteId=%s'%(key,busRoute_id)
savename='data/buspos.xml'
req.urlretrieve(url, savename)

('data/buspos.xml', <http.client.HTTPMessage at 0x159bdbe38b0>)

In [68]:
xml=open(savename,'r',encoding='utf-8').read()
soup=bs(xml, 'xml')
busPos=[]
plainNos=[]
item_list=soup.find_all('itemList')
for item in item_list:
    plainNo=item.find('plainNo').text
    gpsX=item.find('gpsX').text
    gpsY=item.find('gpsY').text
    plainNos.append('plainNo')
    busPos.append([float(gpsY), float(gpsX)])
print(busPos)

[[37.461707, 126.874573], [37.474676, 126.866941], [37.480703, 126.864599], [37.475912, 126.88141], [37.478716, 126.893246], [37.480221, 126.906507], [37.488236, 126.928496], [37.496573, 126.927759], [37.502971, 126.936023], [37.507245, 126.94008], [37.512604, 126.950645], [37.520393, 126.960733], [37.528957, 126.967685], [37.535269, 126.973885], [37.560904, 126.977597], [37.562275, 126.98154], [37.566073, 126.979429], [37.548084, 126.971689], [37.527936, 126.966633], [37.515542, 126.957417], [37.513871, 126.944313], [37.502006, 126.934353], [37.497842, 126.92786], [37.486437, 126.929172], [37.483775, 126.925063], [37.481987, 126.915126], [37.467261, 126.868646]]


In [69]:
busPos_arr=np.array(busPos)
busPos_arr


array([[ 37.461707, 126.874573],
       [ 37.474676, 126.866941],
       [ 37.480703, 126.864599],
       [ 37.475912, 126.88141 ],
       [ 37.478716, 126.893246],
       [ 37.480221, 126.906507],
       [ 37.488236, 126.928496],
       [ 37.496573, 126.927759],
       [ 37.502971, 126.936023],
       [ 37.507245, 126.94008 ],
       [ 37.512604, 126.950645],
       [ 37.520393, 126.960733],
       [ 37.528957, 126.967685],
       [ 37.535269, 126.973885],
       [ 37.560904, 126.977597],
       [ 37.562275, 126.98154 ],
       [ 37.566073, 126.979429],
       [ 37.548084, 126.971689],
       [ 37.527936, 126.966633],
       [ 37.515542, 126.957417],
       [ 37.513871, 126.944313],
       [ 37.502006, 126.934353],
       [ 37.497842, 126.92786 ],
       [ 37.486437, 126.929172],
       [ 37.483775, 126.925063],
       [ 37.481987, 126.915126],
       [ 37.467261, 126.868646]])

In [71]:
tooltip="클릭해주세요"
m=folium.Map(location=[37.461707, 126.874573], zoom_start=12)
plugins.MarkerCluster(busPos_arr, popups=plainNos).add_to(m)
m.save(os.path.join('data', 'cctv_1.html'))
m